// The "Blueprint" tab's data model + assembly helpers. The actual content lives
// in blueprintData.ts (generated by documenting the NARUKAMI source, subsystem by
// subsystem) so it can be regenerated without touching this logic. The whole
// point of the tab: anyone can copy this spec, hand it to their own Claude, and
// rebuild the app from scratch.

export interface BlueprintSection {
  /** Human title, e.g. "Backend HTTP API". */
  title: string;
  /** Stable slug used for the table-of-contents anchor + scroll target. */
  anchor: string;
  /** One-line summary shown as a hint. */
  summary: string;
  /** The section body as GitHub-flavored Markdown (starts with a `##` heading). */
  markdown: string;
}

export interface Blueprint {
  title: string;
  /** Free-text date the content was generated (kept out of code paths that must
   *  stay deterministic). Empty when unknown. */
  generatedAt: string;
  /** Front-matter Markdown: what the app is + architecture + reading order. */
  intro: string;
  /** A short ready-to-paste instruction for the reader's own Claude. */
  preamble: string;
  /** Preferred section order, by anchor. Unlisted sections are appended. */
  order: string[];
  sections: BlueprintSection[];
}

import { BLUEPRINT_DATA } from './blueprintData';

export const BLUEPRINT: Blueprint = BLUEPRINT_DATA;

// Sections in the preferred reading order, with any not named in `order`
// appended in their natural order. Deduped by anchor.
export function orderedSections(bp: Blueprint): BlueprintSection[] {
  const byAnchor = new Map(bp.sections.map((s) => [s.anchor, s]));
  const seen = new Set<string>();
  const out: BlueprintSection[] = [];
  for (const a of bp.order) {
    const s = byAnchor.get(a);
    if (s && !seen.has(a)) {
      out.push(s);
      seen.add(a);
    }
  }
  for (const s of bp.sections) {
    if (!seen.has(s.anchor)) {
      out.push(s);
      seen.add(s.anchor);
    }
  }
  return out;
}

// The entire blueprint as one Markdown document — what the "Copy all" / download
// actions hand off. Sections are separated by horizontal rules.
export function blueprintMarkdown(bp: Blueprint): string {
  const parts: string[] = [`# ${bp.title}`];
  if (bp.generatedAt) parts.push(`_Generated ${bp.generatedAt} from the NARUKAMI source._`);
  if (bp.preamble) parts.push(bp.preamble);
  if (bp.intro) parts.push(bp.intro);
  for (const s of orderedSections(bp)) parts.push(s.markdown);
  return `${parts.join('\n\n---\n\n')}\n`;
}
